id: P005426
initial_creation_type: ocr
source_metadata:
  id: bdr:W23828
  title: གསུང་འབུམ། བསོད་ནམས་གྲགས་པ།
  author: ''
  volumes:
    90baf574db964f2f926c9bd4edfaf90f:
      image_group_id: I3696
      title: ''
      volume_number: 1
      total_pages: 336
    2147cddf943a408583a5b42baa529109:
      image_group_id: I3697
      title: ''
      volume_number: 2
      total_pages: 354
    877a00d67c334352bf3be749b0eeaced:
      image_group_id: I3698
      title: ''
      volume_number: 3
      total_pages: 510
    ce6908d43ca644bc9ce6e46c2b960996:
      image_group_id: I3699
      title: ''
      volume_number: 4
      total_pages: 458
    8a15c6fc762c469888cc14f9d67c5f1e:
      image_group_id: I3700
      title: ''
      volume_number: 5
      total_pages: 470
    077214a7e9d74183aa1438158c9ed153:
      image_group_id: I3701
      title: ''
      volume_number: 6
      total_pages: 536
    cbd49a47cffc43f2a80b819cd6bd4910:
      image_group_id: I3702
      title: ''
      volume_number: 7
      total_pages: 330
    1d07e33953da45afaeac851a4a70b3f8:
      image_group_id: I3703
      title: ''
      volume_number: 8
      total_pages: 726
    cef4523e3e3c4907b30b13f062d966f1:
      image_group_id: I3704
      title: ''
      volume_number: 9
      total_pages: 682
    96faf0c136c2439bb36716f2c7072206:
      image_group_id: I3705
      title: ''
      volume_number: 10
      total_pages: 560
    fb219dccb64b45ba841f9918b8aa96d4:
      image_group_id: I3706
      title: ''
      volume_number: 11
      total_pages: 554
    b7df68b96ac64d63bd40e9248d96f594:
      image_group_id: I3707
      title: ''
      volume_number: 12
      total_pages: 322
