id: I61663426
legacy_id: P005426
ocr_import_info:
  bdrc_scan_id: W23828
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T18:17:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:47:16.532291+00:00'
last_modified: 2022-09-02 12:50:02.049521
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23828
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23828
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བསོད་ནམས་གྲགས་པ།
  author: པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7470139371633414
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I3703:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3703
      total_pages: 726
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3703.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8138765506383073
    legacy_id: v008
  I3696:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3696
      total_pages: 336
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3696.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7248270082845388
    legacy_id: v001
  I3702:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3702
      total_pages: 330
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3702.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7219117139826985
    legacy_id: v007
  I3699:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3699
      total_pages: 458
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3699.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7573511272836251
    legacy_id: v004
  I3697:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3697
      total_pages: 354
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3697.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7392626016597884
    legacy_id: v002
  I3700:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3700
      total_pages: 470
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3700.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7765529890854213
    legacy_id: v005
  I3706:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3706
      total_pages: 554
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3706.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6712129999499129
    legacy_id: v011
  I3701:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3701
      total_pages: 536
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3701.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7018058180037141
    legacy_id: v006
  I3704:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3704
      total_pages: 682
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3704.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7648116983484202
    legacy_id: v009
  I3698:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3698
      total_pages: 510
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3698.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7476960992498152
    legacy_id: v003
  I3705:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3705
      total_pages: 560
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3705.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7010707193445908
    legacy_id: v010
  I3707:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3707
      total_pages: 322
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3707.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8161094610221914
    legacy_id: v012
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
