id: I61663426
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T18:20:35+00:00'
last_modified: '2022-06-08T03:00:29.714926+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23828
  title: གསུང་འབུམ། བསོད་ནམས་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D22B:
      image_group_id: I3696
      title: ''
      total_pages: 336
      order: 1
      base_file: D22B.txt
    BAC9:
      image_group_id: I3697
      title: ''
      total_pages: 354
      order: 2
      base_file: BAC9.txt
    ECCC:
      image_group_id: I3698
      title: ''
      total_pages: 510
      order: 3
      base_file: ECCC.txt
    5A29:
      image_group_id: I3699
      title: ''
      total_pages: 458
      order: 4
      base_file: 5A29.txt
    '3581':
      image_group_id: I3700
      title: ''
      total_pages: 470
      order: 5
      base_file: 3581.txt
    BAB8:
      image_group_id: I3701
      title: ''
      total_pages: 536
      order: 6
      base_file: BAB8.txt
    ED64:
      image_group_id: I3702
      title: ''
      total_pages: 330
      order: 7
      base_file: ED64.txt
    6F6E:
      image_group_id: I3703
      title: ''
      total_pages: 726
      order: 8
      base_file: 6F6E.txt
    391C:
      image_group_id: I3704
      title: ''
      total_pages: 682
      order: 9
      base_file: 391C.txt
    63F9:
      image_group_id: I3705
      title: ''
      total_pages: 560
      order: 10
      base_file: 63F9.txt
    C354:
      image_group_id: I3706
      title: ''
      total_pages: 554
      order: 11
      base_file: C354.txt
    D54B:
      image_group_id: I3707
      title: ''
      total_pages: 322
      order: 12
      base_file: D54B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
